2024-12-26 23:17:33,388 ERROR: Exception on /admin/new_crew [GET] [in /home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 103, in new_crew
    return render_template('admin/new_crew.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
         ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/equist/Programming/ports-game/ports/src/templates/admin/new_crew.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/equist/Programming/ports-game/ports/src/templates/base.html", line 49, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/templates/admin/new_crew.html", line 6, in block 'content'
    {{form.hidden_tag()}}
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/jinja2/environment.py", line 487, in getattr
    return getattr(obj, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'form' is undefined
2024-12-27 17:19:48,743 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:31]
2024-12-28 21:15:49,827 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2024-12-28 21:15:52,705 ERROR: Exception on /handle_transaction/2/1/diamonds/sell [POST] [in /home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: crew.rice_count

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 114, in handle_transaction
    crew = Crew.query.get_or_404(crew_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/flask_sqlalchemy/query.py", line 30, in get_or_404
    rv = self.get(ident)
         ^^^^^^^^^^^^^^^
  File "<string>", line 2, in get
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 386, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 1127, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/query.py", line 1136, in _get_impl
    return self.session._get_impl(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 3873, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/loading.py", line 694, in load_on_pk_identity
    session.execute(
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2362, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 2247, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/orm/context.py", line 305, in orm_execute_statement
    result = conn.execute(
             ^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2355, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/equist/Programming/ports-game/ports/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 941, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: crew.rice_count
[SQL: SELECT crew.id AS crew_id, crew.name AS crew_name, crew.color AS crew_color, crew.max_carry AS crew_max_carry, crew.current_carry AS crew_current_carry, crew.balance AS crew_balance, crew.rice_count AS crew_rice_count, crew.tea_count AS crew_tea_count, crew.wine_count AS crew_wine_count, crew.spice_count AS crew_spice_count, crew.gold_count AS crew_gold_count, crew.diamonds_count AS crew_diamonds_count, crew.slaves_count AS crew_slaves_count 
FROM crew 
WHERE crew.id = ?]
[parameters: (1,)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
