2025-02-24 10:55:31,333 ERROR: Exception on /admin [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 24, in admin
    return render_template("admin/admin.html", title="Admin")
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/equist/.local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/equist/.local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/equist/Programming/ports-game/ports/src/templates/admin/admin.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/equist/Programming/ports-game/ports/src/templates/base.html", line 49, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/templates/admin/admin.html", line 12, in block 'content'
    <form action="{{ url_for('list_crews') }}" method="get" class="mx-2">
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/equist/.local/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'list_crews'. Did you mean 'new_crew' instead?
2025-02-24 10:56:40,136 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-02-24 10:59:47,048 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-02 20:59:32,110 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-02 21:46:27,960 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-02 21:46:44,338 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 21:58:00,638 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 21:58:08,686 ERROR: Exception on /admin [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1482, in full_dispatch_request
    rv = self.preprocess_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1974, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 14, in check_game_over
    if datetime.now(timezone.utc) >= timer.end_time:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't compare offset-naive and offset-aware datetimes
2025-03-06 21:59:14,866 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:15:55,839 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:25:25,783 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:32:26,814 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:34:33,766 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:35:05,521 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:35:33,078 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:35:51,985 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:36:08,009 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:46:00,427 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:46:43,465 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:46:46,844 ERROR: Exception on /index [GET] [in /home/equist/.local/lib/python3.13/site-packages/flask/app.py:1414]
Traceback (most recent call last):
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/equist/Programming/ports-game/ports/src/routes.py", line 64, in index
    return render_template("index.html", title="Home")
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 151, in render_template
    return _render(app, template, context)
  File "/home/equist/.local/lib/python3.13/site-packages/flask/templating.py", line 132, in _render
    rv = template.render(context)
  File "/home/equist/.local/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/equist/.local/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/equist/Programming/ports-game/ports/src/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/equist/Programming/ports-game/ports/src/templates/base.html", line 73, in top-level template code
    <a class="nav-link" aria-current="page" href="{{ url_for('manual') }}">Manual</a>
    ^^^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/equist/.local/lib/python3.13/site-packages/flask/app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/equist/.local/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'manual'. Did you mean 'admin' instead?
2025-03-06 22:48:01,743 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 22:48:13,643 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 23:02:20,094 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-06 23:10:45,376 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
2025-03-23 20:50:02,302 INFO: Ports game [in /home/equist/Programming/ports-game/ports/src/__init__.py:34]
